version: '3.8'

services:
  dubrecord:
    build: .
    container_name: dubrecord
    # environment:
    #   tg_token: 
    #   tg_api_id: 
    #   tg_api_hash: 
    #   app_mode: 
    #   app_host: 
      # app_port: ""     # Порт приложения
    # Переадресация портов (пример, если меняете укажите)
    # ports:
    #   - "8000:8000"  # внешний:внутренний порт
    # Монтирование томов (если нужно)
    # volumes:
    #   - ./data:/app/data
    restart: unless-stopped
    # command: ["uv", "run", "start"] # если нужно переопределить команду запуска
